---
title: "table"
author: "Emre Anakok"
date: "2024-08-12"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
res_grad_LM = read.table("fair_grad_LM.csv",header=T,sep=",",row.names = 1)
res_grad_LM$median_rank = res_grad_LM$median_rank+1
```

```{r}
table1=res_grad_LM[res_grad_LM$ecological_rank %in% c(0:5),][c("median_rank","median_score","features","sign")]
colnames(table1) = c("Median rank","Median score","Features","Grad sign")
table1$`Median score` = as.character(signif(table1$`Median score`,3))
table1$`Median score`[substr(table1$`Median score`,1,1)!="-"]=paste0("+",table1$`Median score`[substr(table1$`Median score`,1,1)!="-"])

cat(kable(table1,digits=2,row.names = FALSE,format="latex")%>%
  kable_paper("striped", full_width = F))
```


```{r}
table2=res_grad_LM[res_grad_LM$land_use_rank %in% c(0:5),][c("median_rank","median_score","plant","features","sign")]
colnames(table2) = c("Median rank","Median score","Plant","Features","Grad sign")
table2$`Median score` = as.character(signif(table2$`Median score`,3))
table2$`Median score`[substr(table2$`Median score`,1,1)!="-"]=paste0("+",table2$`Median score`[substr(table2$`Median score`,1,1)!="-"])

cat(kable(table2,digits=2,row.names = FALSE,format="latex")%>%
  kable_paper("striped", full_width = F))
```

```{r}
table3=res_grad_LM[res_grad_LM$features=="Temperature",][0:5,][c("median_rank","median_score","plant","features","sign")]
colnames(table3) = c("Median rank","Median score","Plant","Features","Grad sign")
table3$`Median score` = as.character(signif(table3$`Median score`,3))
table3$`Median score`[substr(table3$`Median score`,1,1)!="-"]=paste0("+",table3$`Median score`[substr(table3$`Median score`,1,1)!="-"])
cat(kable(table3,digits=2,row.names = FALSE,format="latex")%>%
  kable_paper("striped", full_width = F))
```


```{r}
table4=res_grad_LM[res_grad_LM$features=="Y",][0:5,][c("median_rank","median_score","plant","features","sign")]
colnames(table4) = c("Median rank","Median score","Plant","Features","Grad sign")
table4$`Median score` = as.character(signif(table4$`Median score`,3))
table4$`Median score`[substr(table4$`Median score`,1,1)!="-"]=paste0("+",table4$`Median score`[substr(table4$`Median score`,1,1)!="-"])
cat(kable(table4,digits=2,row.names = FALSE,format="latex")%>%
  kable_paper("striped", full_width = F))
```

```{r}
res_grad_LM0 = read.table("res_grad_LM.csv",header=T,sep=",",row.names = 1)
res_grad_LM = read.table("fair_grad_LM.csv",header=T,sep=",",row.names = 1)

couple0 = paste(res_grad_LM0$features,res_grad_LM0$plant)
couple1 = paste(res_grad_LM$features,res_grad_LM$plant)
match0_1 = match(couple0,couple1)

fair_rank = res_grad_LM$median_rank[match0_1]
print(cor(res_grad_LM0$median_rank,fair_rank,method="spearman"))
print(cor(res_grad_LM0$median_rank[0:50],fair_rank[0:50],method="spearman"))
```

```{r}
truc = c()
for (k in 1:length(fair_rank)){
  truc=c(truc,cor(res_grad_LM0$median_rank[1:k],fair_rank[1:k],method="spearman"))
}
```

```{r}
pch0= rep(c(T,F),c(100,length(res_grad_LM0$median_rank)-100))
pch1=(fair_rank<=(sort(fair_rank)[100]))

color0 = rep("black",length(pch0))
color0[pch0&pch1] = "brown3"
color0[pch0&!pch1] = "cornflowerblue"
color0[!pch0&pch1] = "chartreuse4"

par(pty="s")
plot(res_grad_LM0$median_rank,
     fair_rank,cex=0.5,pch=16,
     col=color0)
```



