---
title: "table"
author: "Emre Anakok"
date: "2024-08-09"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(kableExtra)
```



```{r, fig.dim=c(5, 3),echo=FALSE}
X2=read.table("results_for_rmd/res2/res.csv",sep=",",header=T,row.names = 1)
X4=read.table("results_for_rmd/res4/res.csv",sep=",",header=T,row.names = 1)
X8=read.table("results_for_rmd/res8/res.csv",sep=",",header=T,row.names = 1)
X10=read.table("results_for_rmd/res10/res.csv",sep=",",header=T,row.names = 1)
X14=read.table("results_for_rmd/res14/res.csv",sep=",",header=T,row.names = 1)
X15=read.table("results_for_rmd/res15/res.csv",sep=",",header=T,row.names = 1)

restable2 = matrix(colMeans(X2[5:ncol(X2)]),nrow=3)
restable4 = matrix(colMeans(X4[5:ncol(X4)]),nrow=3)
restable8 = matrix(colMeans(X8[5:ncol(X8)]),nrow=3)
restable10 = matrix(colMeans(X10[5:ncol(X10)]),nrow=3)
restable14 = matrix(colMeans(X14[5:ncol(X10)]),nrow=3)
restable15 = matrix(colMeans(X15[5:ncol(X10)]),nrow=3)

restable = rbind(restable2,restable4,restable8,restable10,restable14 ,restable15 )
```


```{r, fig.dim=c(5, 3),echo=FALSE}
colnames(restable) = c("GraphSVX ","Grad","Grad x Input","IG","Grad LM","IG LM")
rownames(restable)= rep(c("+","-","AUC"),6)

cat(
  kable(restable,digits = 3,format="latex") %>%
  kable_paper("striped", full_width = T)%>%
  pack_rows("2.A", 1, 3) %>%
  pack_rows("2.B", 4, 6) %>%
  pack_rows("2.C", 7, 9) %>%
  pack_rows("2.D", 10, 12)%>%
  pack_rows("2.E", 13, 15)%>%
  pack_rows("2.F", 16, 18)%>%
  row_spec(0:18, align = "c")%>%
  row_spec(c(3, 6, 9,12,15), extra_latex_after = "\\hline\\addlinespace[0.5cm]")%>%
  column_spec(1,border_right=T))
```

